"""Tests for the per-user daily cap on POST /art/generate.

Image generation is the one endpoint where a single logged-in user can
run up a bill on their own, so it carries a per-user daily cap on top of
the global breaker. Exhausting it is a normal state, not a failure: the
response has to tell the client both *what* happened and *when* to come
back, in a form it can render without printing an error.
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncGenerator
from datetime import UTC, datetime, timedelta
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

import alchymine.db.models  # noqa: F401 — register models with metadata
from alchymine.api.auth import get_current_user
from alchymine.api.deps import get_db_session, set_db_engine
from alchymine.api.main import app
from alchymine.api.routers.generative_art import _gemini_dependency
from alchymine.config import get_settings
from alchymine.db.base import Base
from alchymine.db.models import User
from alchymine.db.usage_counters import (
    METER_ART_GENERATIONS,
    CostCeilingExceeded,
    get_count,
)
from alchymine.llm.gemini import GeminiImageResult

TEST_USER_ID = "user-1"
OTHER_USER_ID = "user-cap-other"


def _image() -> GeminiImageResult:
    return GeminiImageResult(
        image_bytes=b"\x89PNG\r\n\x1a\n",
        mime_type="image/png",
        prompt="a serene forest",
        model="gemini-test",
        generated_at=datetime.now(UTC),
    )


@pytest.fixture
def client(tmp_path) -> TestClient:
    """TestClient where the route and the cost meter share one SQLite DB.

    Both must point at the same engine: the route reads the user through
    the injected session while the meter opens its own session from the
    ``deps`` singleton, exactly as they do in production.
    """
    engine = create_async_engine(
        "sqlite+aiosqlite://",
        connect_args={"check_same_thread": False},
        echo=False,
    )
    factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async def _setup() -> None:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
        async with factory() as session:
            session.add(User(id=TEST_USER_ID, email="cap@example.com", is_active=True))
            session.add(User(id=OTHER_USER_ID, email="other@example.com", is_active=True))
            await session.commit()

    loop = asyncio.new_event_loop()
    loop.run_until_complete(_setup())

    async def _override_session() -> AsyncGenerator[AsyncSession, None]:
        async with factory() as session:
            try:
                yield session
                await session.commit()
            except Exception:
                await session.rollback()
                raise

    gemini = MagicMock()
    gemini.is_available = True
    gemini.generate_image = AsyncMock(side_effect=lambda _prompt: _image())

    app.dependency_overrides[get_db_session] = _override_session
    app.dependency_overrides[_gemini_dependency] = lambda: gemini
    set_db_engine(engine)

    # Keep generated bytes in a temp dir. Setting ART_CACHE_DIR is not enough
    # because get_settings is lru_cached by the time the fixture runs.
    with patch("alchymine.llm.art_storage.get_art_cache_root", return_value=tmp_path):
        tc = TestClient(app)
        tc.gemini = gemini  # type: ignore[attr-defined] — handy for call assertions
        try:
            yield tc
        finally:
            app.dependency_overrides.pop(get_db_session, None)
            app.dependency_overrides.pop(_gemini_dependency, None)
            set_db_engine(None)
            loop.run_until_complete(engine.dispose())
            loop.close()


def _as_user(user_id: str) -> None:
    async def _current() -> dict:
        return {"sub": user_id, "email": f"{user_id}@example.com"}

    app.dependency_overrides[get_current_user] = _current


class TestDailyCap:
    def test_allows_generations_up_to_the_cap(self, client: TestClient) -> None:
        cap = get_settings().daily_art_generations_per_user
        for _ in range(cap):
            assert client.post("/api/v1/art/generate", json={}).status_code == 201

    def test_blocks_the_generation_past_the_cap(self, client: TestClient) -> None:
        cap = get_settings().daily_art_generations_per_user
        for _ in range(cap):
            client.post("/api/v1/art/generate", json={})

        response = client.post("/api/v1/art/generate", json={})
        assert response.status_code == 429

    def test_capped_response_is_machine_readable(self, client: TestClient) -> None:
        for _ in range(get_settings().daily_art_generations_per_user):
            client.post("/api/v1/art/generate", json={})

        detail = client.post("/api/v1/art/generate", json={}).json()["detail"]
        assert detail["code"] == "daily_art_cap_reached"
        assert datetime.fromisoformat(detail["retry_at"]) > datetime.now(UTC)
        # Shown to a person, so it follows the house copy rules.
        assert "—" not in detail["message"]
        for banned in ("delve", "leverage", "robust", "seamless", "utilize", "ensure"):
            assert banned not in detail["message"].lower()

    def test_capped_request_never_reaches_gemini(self, client: TestClient) -> None:
        cap = get_settings().daily_art_generations_per_user
        for _ in range(cap):
            client.post("/api/v1/art/generate", json={})
        calls_before = client.gemini.generate_image.call_count  # type: ignore[attr-defined]

        client.post("/api/v1/art/generate", json={})

        assert client.gemini.generate_image.call_count == calls_before  # type: ignore[attr-defined]

    def test_cap_is_per_user(self, client: TestClient) -> None:
        cap = get_settings().daily_art_generations_per_user
        for _ in range(cap):
            client.post("/api/v1/art/generate", json={})
        assert client.post("/api/v1/art/generate", json={}).status_code == 429

        _as_user(OTHER_USER_ID)
        try:
            # A different user starts with a full allowance.
            assert client.post("/api/v1/art/generate", json={}).status_code == 201
        finally:
            app.dependency_overrides.pop(get_current_user, None)

    def test_cap_resets_on_the_next_utc_day(
        self, client: TestClient, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        cap = get_settings().daily_art_generations_per_user
        for _ in range(cap):
            client.post("/api/v1/art/generate", json={})
        assert client.post("/api/v1/art/generate", json={}).status_code == 429

        monkeypatch.setattr(
            "alchymine.db.usage_counters.current_period_key",
            lambda *_args, **_kwargs: "2099-01-01",
        )
        assert client.post("/api/v1/art/generate", json={}).status_code == 201

    def test_unavailable_gemini_does_not_spend_the_allowance(self, client: TestClient) -> None:
        """A 204 costs nothing, so it must not burn one of the day's three."""
        client.gemini.is_available = False  # type: ignore[attr-defined]

        assert client.post("/api/v1/art/generate", json={}).status_code == 204

        counted = asyncio.run(get_count(scope=TEST_USER_ID, meter=METER_ART_GENERATIONS))
        assert counted == 0


class TestBrandLogoDailyCap:
    """POST /art/brand/logo spends the same per-user allowance.

    A sibling endpoint on the same paid generator would otherwise be a
    way around the cap the studio route enforces.
    """

    def test_allows_logos_up_to_the_cap(self, client: TestClient) -> None:
        cap = get_settings().daily_art_generations_per_user
        for _ in range(cap):
            assert client.post("/api/v1/art/brand/logo").status_code == 201

    def test_blocks_the_logo_past_the_cap(self, client: TestClient) -> None:
        for _ in range(get_settings().daily_art_generations_per_user):
            client.post("/api/v1/art/brand/logo")

        response = client.post("/api/v1/art/brand/logo")
        assert response.status_code == 429
        assert response.json()["detail"]["code"] == "daily_art_cap_reached"

    def test_capped_request_never_reaches_gemini(self, client: TestClient) -> None:
        for _ in range(get_settings().daily_art_generations_per_user):
            client.post("/api/v1/art/brand/logo")
        calls_before = client.gemini.generate_image.call_count  # type: ignore[attr-defined]

        client.post("/api/v1/art/brand/logo")

        assert client.gemini.generate_image.call_count == calls_before  # type: ignore[attr-defined]

    def test_cap_is_per_user(self, client: TestClient) -> None:
        for _ in range(get_settings().daily_art_generations_per_user):
            client.post("/api/v1/art/brand/logo")
        assert client.post("/api/v1/art/brand/logo").status_code == 429

        _as_user(OTHER_USER_ID)
        try:
            assert client.post("/api/v1/art/brand/logo").status_code == 201
        finally:
            app.dependency_overrides.pop(get_current_user, None)

    def test_logos_and_studio_images_share_one_allowance(self, client: TestClient) -> None:
        """Three total across both routes, not three each."""
        cap = get_settings().daily_art_generations_per_user
        assert cap == 3, "test assumes the default cap"

        assert client.post("/api/v1/art/generate", json={}).status_code == 201
        assert client.post("/api/v1/art/brand/logo").status_code == 201
        assert client.post("/api/v1/art/generate", json={}).status_code == 201

        assert client.post("/api/v1/art/brand/logo").status_code == 429


class TestAllowanceRefund:
    """A generation that delivers nothing must not cost the user a slot."""

    def test_a_204_does_not_spend_the_allowance(self, client: TestClient) -> None:
        client.gemini.generate_image = AsyncMock(return_value=None)  # type: ignore[attr-defined]

        assert client.post("/api/v1/art/generate", json={}).status_code == 204

        counted = asyncio.run(get_count(scope=TEST_USER_ID, meter=METER_ART_GENERATIONS))
        assert counted == 0

    def test_repeated_failures_leave_the_day_intact(self, client: TestClient) -> None:
        """A bad night for the generator must not burn the whole quota."""
        client.gemini.generate_image = AsyncMock(return_value=None)  # type: ignore[attr-defined]
        for _ in range(10):
            assert client.post("/api/v1/art/generate", json={}).status_code == 204

        # The generator recovers; the user still has their full allowance.
        client.gemini.generate_image = AsyncMock(side_effect=lambda _p: _image())  # type: ignore[attr-defined]
        cap = get_settings().daily_art_generations_per_user
        for _ in range(cap):
            assert client.post("/api/v1/art/generate", json={}).status_code == 201

    def test_a_failing_generator_does_not_spend_the_allowance(self, client: TestClient) -> None:
        """An exception on the way out is also 'delivered nothing'."""
        client.gemini.generate_image = AsyncMock(  # type: ignore[attr-defined]
            side_effect=RuntimeError("gemini exploded")
        )

        client.post("/api/v1/art/generate", json={})

        counted = asyncio.run(get_count(scope=TEST_USER_ID, meter=METER_ART_GENERATIONS))
        assert counted == 0

    def test_a_tripped_global_breaker_does_not_spend_the_allowance(
        self, client: TestClient
    ) -> None:
        """A system-wide pause is not the user's fault, so it is not their quota."""
        client.gemini.generate_image = AsyncMock(  # type: ignore[attr-defined]
            side_effect=CostCeilingExceeded(
                meter="llm_calls",
                scope="global",
                retry_at=datetime.now(UTC) + timedelta(hours=1),
            )
        )

        assert client.post("/api/v1/art/generate", json={}).status_code == 503

        counted = asyncio.run(get_count(scope=TEST_USER_ID, meter=METER_ART_GENERATIONS))
        assert counted == 0

    def test_a_delivered_image_does_spend_the_allowance(self, client: TestClient) -> None:
        """The refund must not undo a real generation."""
        assert client.post("/api/v1/art/generate", json={}).status_code == 201

        counted = asyncio.run(get_count(scope=TEST_USER_ID, meter=METER_ART_GENERATIONS))
        assert counted == 1

    def test_brand_logo_refunds_too(self, client: TestClient) -> None:
        client.gemini.generate_image = AsyncMock(return_value=None)  # type: ignore[attr-defined]

        assert client.post("/api/v1/art/brand/logo").status_code == 204

        counted = asyncio.run(get_count(scope=TEST_USER_ID, meter=METER_ART_GENERATIONS))
        assert counted == 0

    def test_refund_credits_the_day_that_was_charged(
        self, client: TestClient, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A request straddling UTC midnight refunds the day it charged.

        Charged at 23:59:59, refunded at 00:00:01: reading the clock again
        at refund time would credit the new day, whose counter row does not
        exist yet, and the clamp would turn that into a silent no-op.
        """
        charged_day = "2026-08-12"
        rolled_day = "2026-08-13"
        # The charge reads the clock once; every read after it is past midnight.
        reads = iter([charged_day])
        monkeypatch.setattr(
            "alchymine.db.usage_counters.current_period_key",
            lambda *_args, **_kwargs: next(reads, rolled_day),
        )
        client.gemini.generate_image = AsyncMock(return_value=None)  # type: ignore[attr-defined]

        assert client.post("/api/v1/art/generate", json={}).status_code == 204

        charged = asyncio.run(
            get_count(scope=TEST_USER_ID, meter=METER_ART_GENERATIONS, period_key=charged_day)
        )
        rolled = asyncio.run(
            get_count(scope=TEST_USER_ID, meter=METER_ART_GENERATIONS, period_key=rolled_day)
        )
        assert charged == 0, "the charged day kept the slot"
        assert rolled == 0, "the refund landed on the day after the charge"


class TestMeterDownIsNotACap:
    """429 means 'you spent your allowance'. 503 means 'our meter is down'."""

    def test_unreachable_meter_returns_503_not_429(self, client: TestClient) -> None:
        with patch(
            "alchymine.api.routers.generative_art.consume",
            AsyncMock(
                side_effect=CostCeilingExceeded(
                    meter=METER_ART_GENERATIONS,
                    scope=TEST_USER_ID,
                    retry_at=datetime.now(UTC) + timedelta(hours=1),
                    reason="meter_unavailable",
                )
            ),
        ):
            response = client.post("/api/v1/art/generate", json={})

        assert response.status_code == 503
        assert response.json()["detail"]["code"] == "llm_temporarily_unavailable"

    def test_unreachable_meter_does_not_claim_the_cap_is_spent(self, client: TestClient) -> None:
        """Telling users their quota is gone when it isn't would be a lie."""
        with patch(
            "alchymine.api.routers.generative_art.consume",
            AsyncMock(
                side_effect=CostCeilingExceeded(
                    meter=METER_ART_GENERATIONS,
                    scope=TEST_USER_ID,
                    retry_at=datetime.now(UTC) + timedelta(hours=1),
                    reason="meter_unavailable",
                )
            ),
        ):
            body = client.post("/api/v1/art/generate", json={}).text

        assert "daily_art_cap_reached" not in body

    def test_spent_cap_still_returns_429(self, client: TestClient) -> None:
        for _ in range(get_settings().daily_art_generations_per_user):
            client.post("/api/v1/art/generate", json={})

        assert client.post("/api/v1/art/generate", json={}).status_code == 429
