"""Wealth Engine — deterministic financial calculations.

CRITICAL: All calculations in this package MUST be deterministic.
Financial values are NEVER generated by LLM. AI only narrates
pre-validated numbers.

Public API:
    WealthArchetype              — Dataclass for wealth archetype metadata
    WEALTH_ARCHETYPES            — Registry of all 8 wealth archetypes
    map_wealth_archetype         — Map inputs to a WealthArchetype
    get_wealth_archetype_scores  — Expose raw scores for debugging
    prioritize_levers            — Order wealth levers by priority
    ActivationPlan               — 90-day plan dataclass
    PlanPhase                    — Single phase in the activation plan
    generate_activation_plan     — Generate a 90-day wealth plan
    Debt                         — Single debt obligation
    DebtType                     — Debt type classification enum
    MonthlyEntry                 — Single month in a payoff schedule
    PayoffSchedule               — Per-debt month-by-month schedule
    PayoffResult                 — Complete strategy result with schedules
    StrategyComparison           — Side-by-side snowball vs. avalanche
    calculate_snowball           — Snowball debt payoff strategy
    calculate_avalanche          — Avalanche debt payoff strategy
    compare_strategies           — Compare snowball vs. avalanche
"""

from .archetype import (
    WEALTH_ARCHETYPES,
    WealthArchetype,
    get_wealth_archetype_scores,
    map_wealth_archetype,
)
from .debt import (
    Debt,
    DebtType,
    MonthlyEntry,
    PayoffResult,
    PayoffSchedule,
    StrategyComparison,
    calculate_avalanche,
    calculate_snowball,
    compare_strategies,
)
from .levers import prioritize_levers
from .plan import ActivationPlan, PlanPhase, generate_activation_plan

__all__ = [
    "WEALTH_ARCHETYPES",
    "WealthArchetype",
    "get_wealth_archetype_scores",
    "map_wealth_archetype",
    "prioritize_levers",
    "ActivationPlan",
    "PlanPhase",
    "generate_activation_plan",
    "Debt",
    "DebtType",
    "MonthlyEntry",
    "PayoffSchedule",
    "PayoffResult",
    "StrategyComparison",
    "calculate_snowball",
    "calculate_avalanche",
    "compare_strategies",
]
