"""Wealth Engine — deterministic financial calculations.

CRITICAL: All calculations in this package MUST be deterministic.
Financial values are NEVER generated by LLM. AI only narrates
pre-validated numbers.

Public API:
    WealthArchetype              — Dataclass for wealth archetype metadata
    WEALTH_ARCHETYPES            — Registry of all 8 wealth archetypes
    map_wealth_archetype         — Map inputs to a WealthArchetype
    get_wealth_archetype_scores  — Expose raw scores for debugging
    prioritize_levers            — Order wealth levers by priority
    ActivationPlan               — 90-day plan dataclass
    PlanPhase                    — Single phase in the activation plan
    generate_activation_plan     — Generate a 90-day wealth plan
"""

from .archetype import (
    WEALTH_ARCHETYPES,
    WealthArchetype,
    get_wealth_archetype_scores,
    map_wealth_archetype,
)
from .levers import prioritize_levers
from .plan import ActivationPlan, PlanPhase, generate_activation_plan

__all__ = [
    "WEALTH_ARCHETYPES",
    "WealthArchetype",
    "get_wealth_archetype_scores",
    "map_wealth_archetype",
    "prioritize_levers",
    "ActivationPlan",
    "PlanPhase",
    "generate_activation_plan",
]
