"""Wealth Engine — deterministic financial calculations.

CRITICAL: All calculations in this package MUST be deterministic.
Financial values are NEVER generated by LLM. AI only narrates
pre-validated numbers.
"""
