"""Wealth plan CSV/spreadsheet export.

Converts a 90-day ActivationPlan into a downloadable CSV file
for independent verification. All calculations are deterministic,
so users can audit every step.
"""

from __future__ import annotations

import csv
import io

from alchymine.engine.wealth.plan import ActivationPlan


def plan_to_csv(plan: ActivationPlan) -> str:
    """Convert an ActivationPlan to CSV format.

    Returns a string containing the CSV content ready for download.
    """
    output = io.StringIO()
    writer = csv.writer(output)

    # Header section
    writer.writerow(["Alchymine 90-Day Wealth Activation Plan"])
    writer.writerow(["Wealth Archetype", plan.wealth_archetype])
    writer.writerow([])

    # Phases
    writer.writerow(["Phase", "Days", "Focus Lever", "Actions", "Milestones"])
    for phase in plan.phases:
        start, end = phase.days
        writer.writerow(
            [
                phase.name,
                f"Day {start}-{end}",
                phase.focus_lever.value
                if hasattr(phase.focus_lever, "value")
                else str(phase.focus_lever),
                "; ".join(phase.actions),
                "; ".join(phase.milestones),
            ]
        )

    writer.writerow([])

    # Expanded action items (one per row for task tracking)
    writer.writerow(["Phase", "Day Range", "Lever", "Action Item", "Status"])
    for phase in plan.phases:
        start, end = phase.days
        lever_name = (
            phase.focus_lever.value
            if hasattr(phase.focus_lever, "value")
            else str(phase.focus_lever)
        )
        for action in phase.actions:
            writer.writerow(
                [
                    phase.name,
                    f"Day {start}-{end}",
                    lever_name,
                    action,
                    "",  # Empty status column for user to fill
                ]
            )

    writer.writerow([])

    # Milestones checklist
    writer.writerow(["Phase", "Milestone", "Completed"])
    for phase in plan.phases:
        for milestone in phase.milestones:
            writer.writerow([phase.name, milestone, ""])

    writer.writerow([])

    # Daily habits
    writer.writerow(["Daily Habits"])
    for habit in plan.daily_habits:
        writer.writerow([habit])

    writer.writerow([])

    # Weekly reviews
    writer.writerow(["Weekly Review Checklist"])
    for review in plan.weekly_reviews:
        writer.writerow([review])

    writer.writerow([])
    writer.writerow(
        ["DISCLAIMER: This is not financial advice. All strategies require professional review."]
    )
    writer.writerow(["Generated by Alchymine Wealth Engine - deterministic calculations only."])

    return output.getvalue()
