"""Creative Forge engines — Guilford scoring, Creative DNA, style analysis, projects, collaboration.

CRITICAL: All calculations in this package MUST be deterministic.
Creative assessments are NEVER generated by LLM. AI only narrates
pre-validated scores and recommendations.

Public API:
    Assessment:
        assess_guilford             — Score divergent thinking from responses
        assess_creative_dna         — Tharp-inspired creative preferences
        derive_creative_orientation — Map Life Path to creative orientation

    Style Analysis:
        generate_style_fingerprint  — Combined style profile
        identify_strengths          — Top 3 creative strengths
        identify_growth_areas       — Areas for development
        suggest_mediums             — Recommended creative mediums

    Projects:
        suggest_projects            — Generate project ideas
        estimate_project_scope      — Time/effort estimation

    Collaboration:
        compatibility_score         — 0-1 compatibility between two people
        complementary_strengths     — What each collaborator brings
"""

from .assessment import (
    assess_creative_dna,
    assess_guilford,
    derive_creative_orientation,
)
from .collaboration import (
    compatibility_score,
    complementary_strengths,
)
from .projects import (
    estimate_project_scope,
    suggest_projects,
)
from .style import (
    generate_style_fingerprint,
    identify_growth_areas,
    identify_strengths,
    suggest_mediums,
)

__all__ = [
    # Assessment
    "assess_guilford",
    "assess_creative_dna",
    "derive_creative_orientation",
    # Style
    "generate_style_fingerprint",
    "identify_strengths",
    "identify_growth_areas",
    "suggest_mediums",
    # Projects
    "suggest_projects",
    "estimate_project_scope",
    # Collaboration
    "compatibility_score",
    "complementary_strengths",
]
