"""PDF report renderer using Playwright.

Converts HTML report content to PDF using headless Chromium via the
Playwright library. Supports financial disclaimer injection for wealth
reports and evidence metadata footers.

Playwright is an optional dependency — if it is not installed or browsers
are not available, this module logs a warning and raises a clear error.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Financial disclaimer text injected into wealth-related reports
_FINANCIAL_DISCLAIMER = (
    '<div style="border-top:2px solid #c4a04a;margin-top:2rem;padding-top:1rem;'
    "font-size:0.75rem;color:#888;text-align:center;page-break-inside:avoid;"
    'break-inside:avoid;">'
    "<strong>Financial Disclaimer:</strong> "
    "The information contained in this report is for educational and informational "
    "purposes only and does not constitute financial advice. All financial "
    "calculations are deterministic and should not be used as the sole basis for "
    "any investment or financial decision. Consult a qualified financial advisor "
    "before making financial decisions."
    "</div>"
)

# Evidence metadata footer template
_EVIDENCE_FOOTER = (
    '<div style="border-top:1px solid rgba(255,255,255,0.08);margin-top:1.5rem;'
    "padding-top:0.75rem;font-size:0.7rem;color:#888;text-align:center;"
    'page-break-inside:avoid;break-inside:avoid;">'
    "<p>Report generated by Alchymine — Open-Source Personal Transformation OS</p>"
    "<p>All calculations use deterministic algorithms. Evidence ratings and "
    "methodology are available in the full report.</p>"
    "<p>License: CC-BY-NC-SA 4.0</p>"
    "</div>"
)


def inject_financial_disclaimer(html_content: str) -> str:
    """Inject a financial disclaimer before the closing body tag.

    Parameters
    ----------
    html_content:
        The raw HTML string to modify.

    Returns
    -------
    str
        The HTML with the disclaimer injected before ``</body>``.
    """
    if "</body>" in html_content:
        return html_content.replace("</body>", f"{_FINANCIAL_DISCLAIMER}</body>", 1)
    return html_content + _FINANCIAL_DISCLAIMER


def inject_evidence_footer(html_content: str) -> str:
    """Inject an evidence metadata footer before the closing body tag.

    Parameters
    ----------
    html_content:
        The raw HTML string to modify.

    Returns
    -------
    str
        The HTML with the evidence footer injected before ``</body>``.
    """
    if "</body>" in html_content:
        return html_content.replace("</body>", f"{_EVIDENCE_FOOTER}</body>", 1)
    return html_content + _EVIDENCE_FOOTER


class PlaywrightNotAvailableError(Exception):
    """Raised when Playwright is not installed or browsers are missing."""


class PDFRenderer:
    """Renders HTML content to PDF using Playwright's headless Chromium.

    Example
    -------
    >>> renderer = PDFRenderer()
    >>> pdf_bytes = await renderer.render_pdf("<html><body>Hello</body></html>")
    """

    def __init__(
        self,
        *,
        margin_top: str = "1cm",
        margin_bottom: str = "1cm",
        margin_left: str = "1cm",
        margin_right: str = "1cm",
        print_background: bool = True,
        format_: str = "A4",
    ) -> None:
        self.margin_top = margin_top
        self.margin_bottom = margin_bottom
        self.margin_left = margin_left
        self.margin_right = margin_right
        self.print_background = print_background
        self.format_ = format_

    async def render_pdf(
        self,
        html_content: str,
        output_path: str | None = None,
        *,
        is_wealth_report: bool = False,
        include_evidence_footer: bool = True,
    ) -> bytes:
        """Render HTML content to a PDF document.

        Parameters
        ----------
        html_content:
            Complete HTML document string.
        output_path:
            Optional filesystem path to write the PDF to.
            If ``None``, PDF bytes are returned but not saved to disk.
        is_wealth_report:
            If ``True``, a financial disclaimer is injected into the HTML.
        include_evidence_footer:
            If ``True`` (default), an evidence metadata footer is appended.

        Returns
        -------
        bytes
            The rendered PDF as raw bytes.

        Raises
        ------
        PlaywrightNotAvailableError
            If Playwright is not installed or Chromium is not available.
        """
        # Apply content injections before rendering
        if is_wealth_report:
            html_content = inject_financial_disclaimer(html_content)
        if include_evidence_footer:
            html_content = inject_evidence_footer(html_content)

        try:
            from playwright.async_api import async_playwright
        except ImportError as exc:
            logger.warning(
                "Playwright is not installed. Install it with: "
                "pip install playwright && playwright install chromium"
            )
            raise PlaywrightNotAvailableError(
                "Playwright is not installed. "
                "Install it with: pip install playwright && playwright install chromium"
            ) from exc

        try:
            async with async_playwright() as p:
                browser = await p.chromium.launch(headless=True)
                try:
                    page = await browser.new_page()
                    await page.set_content(html_content, wait_until="networkidle")

                    pdf_bytes = await page.pdf(
                        format=self.format_,
                        print_background=self.print_background,
                        margin={
                            "top": self.margin_top,
                            "bottom": self.margin_bottom,
                            "left": self.margin_left,
                            "right": self.margin_right,
                        },
                        header_template=(
                            '<div style="font-size:8px;text-align:center;width:100%;'
                            'color:#888;">Alchymine Report</div>'
                        ),
                        footer_template=(
                            '<div style="font-size:8px;text-align:center;width:100%;'
                            'color:#888;">Page <span class="pageNumber"></span> of '
                            '<span class="totalPages"></span></div>'
                        ),
                        display_header_footer=True,
                    )
                finally:
                    await browser.close()
        except Exception as exc:
            if "PlaywrightNotAvailableError" in type(exc).__name__:
                raise
            # Catch browser-not-installed or other Playwright errors
            error_msg = str(exc)
            if "Executable doesn't exist" in error_msg or "browserType.launch" in error_msg:
                logger.warning(
                    "Playwright browsers are not installed. Run: playwright install chromium"
                )
                raise PlaywrightNotAvailableError(
                    "Playwright browsers are not installed. Run: playwright install chromium"
                ) from exc
            raise

        # Optionally write to disk
        if output_path is not None:
            path = Path(output_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(pdf_bytes)
            logger.info("PDF written to %s (%d bytes)", output_path, len(pdf_bytes))

        return pdf_bytes
